name       : nasm
version    : 2.13.02
release    : 7
source     :
    - http://www.nasm.us/pub/nasm/releasebuilds/2.13.02/nasm-2.13.02.tar.xz : 8ac3235f49a6838ff7a8d7ef7c19a4430d0deecc0c2d3e3e237b5e9f53291757
    - http://www.nasm.us/pub/nasm/releasebuilds/2.13.02/nasm-2.13.02-xdoc.tar.xz : 7f3adad45c0386edc7a44f92b287f404b423b09b3085a5aac3c16f1deda56f5a
homepage   : http://www.nasm.us/
license    : BSD-2-Clause
summary    : Netwide Assembler
component  : system.devel
description: |
    NASM (Netwide Assembler) is an 80x86 assembler designed for portability and modularity. It includes a disassembler as well.
patterns   :
    - docs :
        - /usr/share/doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install INSTALLROOT="$installdir"
    # Sort out docs
    tar xf $sources/${package}-${version}-xdoc.tar.xz --strip-components=1
    install -D -d -m 00755 $installdir/usr/share/doc/${package}
    install -m 00644 doc/*.txt doc/*.pdf doc/html/*.html $installdir/usr/share/doc/${package}
