name       : nasm
version    : 2.15.05
release    : 17
source     :
    - https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.xz : 3caf6729c1073bf96629b57cee31eeb54f4f8129b01902c73428836550b30a3f
    - https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05-xdoc.tar.xz : 02a260cabb649bf55a06e3dc5abb1413746704156c80afc742b8fc1510262ed1
homepage   : https://www.nasm.us/
license    : BSD-2-Clause
summary    : Netwide Assembler
component  : system.devel
description: |
    NASM (Netwide Assembler) is an 80x86 assembler designed for portability and modularity. It includes a disassembler as well.
patterns   :
    - docs :
        - /usr/share/doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install INSTALLROOT="$installdir"
    # Sort out docs
    tar xf $sources/${package}-${version}-xdoc.tar.xz --strip-components=1
    install -D -d -m 00755 $installdir/usr/share/doc/${package}
    install -m 00644 doc/*.txt doc/*.pdf doc/html/*.html $installdir/usr/share/doc/${package}
