name       : nasm
version    : 2.15.02
release    : 13
source     :
    - https://www.nasm.us/pub/nasm/releasebuilds/2.15.02/nasm-2.15.02.tar.xz : f4fd1329b1713e1ccd34b2fc121c4bcd278c9f91cc4cb205ae8fcd2e4728dd14
    - https://www.nasm.us/pub/nasm/releasebuilds/2.15.02/nasm-2.15.02-xdoc.tar.xz : a2ec81aeb86b61dee8e43bdc561449119a65fb429efa48abdc569dc7471b1981
homepage   : https://www.nasm.us/
license    : BSD-2-Clause
summary    : Netwide Assembler
component  : system.devel
description: |
    NASM (Netwide Assembler) is an 80x86 assembler designed for portability and modularity. It includes a disassembler as well.
patterns   :
    - docs :
        - /usr/share/doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install INSTALLROOT="$installdir"
    # Sort out docs
    tar xf $sources/${package}-${version}-xdoc.tar.xz --strip-components=1
    install -D -d -m 00755 $installdir/usr/share/doc/${package}
    install -m 00644 doc/*.txt doc/*.pdf doc/html/*.html $installdir/usr/share/doc/${package}
