name       : nasm
version    : 2.16.01
release    : 18
source     :
    - https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.xz : c77745f4802375efeee2ec5c0ad6b7f037ea9c87c92b149a9637ff099f162558
    - https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01-xdoc.tar.xz : 801867a71f4c3d513a927ba09b3fa12ef9c7c5c98c0aaafc59c7f342faeab2c9
homepage   : https://www.nasm.us/
license    : BSD-2-Clause
summary    : Netwide Assembler
component  : system.devel
description: |
    NASM (Netwide Assembler) is an 80x86 assembler designed for portability and modularity. It includes a disassembler as well.
patterns   :
    - docs :
        - /usr/share/doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install INSTALLROOT="$installdir"
    # Sort out docs
    tar xf $sources/${package}-${version}-xdoc.tar.xz --strip-components=1
    install -dm 00755 $installdir/usr/share/doc/${package}
    install -m00644 doc/*.txt doc/*.pdf doc/html/*.html $installdir/usr/share/doc/${package}
