name       : nasm
version    : 2.14.01
release    : 10
source     :
    - https://www.nasm.us/pub/nasm/releasebuilds/2.14.01/nasm-2.14.01.tar.xz : c28dfae587d59409a91271971268020ade1809a191fefdffa81e6800609ac014
    - https://www.nasm.us/pub/nasm/releasebuilds/2.14.01/nasm-2.14.01-xdoc.tar.xz : 9925fa156b817cd56837b9b21735ad9e5b35360b469e17f299878466d9401c98
homepage   : https://www.nasm.us/
license    : BSD-2-Clause
summary    : Netwide Assembler
component  : system.devel
description: |
    NASM (Netwide Assembler) is an 80x86 assembler designed for portability and modularity. It includes a disassembler as well.
patterns   :
    - docs :
        - /usr/share/doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install INSTALLROOT="$installdir"
    # Sort out docs
    tar xf $sources/${package}-${version}-xdoc.tar.xz --strip-components=1
    install -D -d -m 00755 $installdir/usr/share/doc/${package}
    install -m 00644 doc/*.txt doc/*.pdf doc/html/*.html $installdir/usr/share/doc/${package}
