name       : nasm
version    : 2.12.02
release    : 5
source     :
    - http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/nasm-2.12.02.tar.xz : 4c866b60c0b1c4ebc715205d007b4640ff4e36af637c9a7deb87b2900e544321
    - http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/nasm-2.12.02-xdoc.tar.xz : 691971caa9357be16585f52b193e44e3f2c262f9ca9314f87f60b3e69d250e09
homepage   : http://www.nasm.us/
license    :
    - BSD-2-Clause
summary    : Netwide Assembler
component  : system.devel
description: |
    NASM (Netwide Assembler) is an 80x86 assembler designed for portability and modularity. It includes a disassembler as well.
patterns   :
    - docs:
        - /usr/share/info
        - /usr/share/doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install INSTALLROOT="$installdir"
    # Sort out docs
    tar xf $sources/${package}-${version}-xdoc.tar.xz --strip-components=1
    install -D -d -m 00755 $installdir/usr/share/doc/${package}
    install -D -d -m 00755 $installdir/usr/share/info
    install -m 00644 doc/*.txt doc/*.ps doc/*.pdf doc/html/*.html $installdir/usr/share/doc/${package}
    install -m 00644 doc/info/* $installdir/usr/share/info/.
